spring:
    application:
        name: pica-historic
    zipkin:
        base-url: http://zipkin-server:9411/
server:
    port: 5004
eureka:
    client:
        service-url:
            defaultZone: http://eureka-server:8761/eureka